// Generated by https://quicktype.io

export interface Character {
    id:               CharacterId;
    name:             string;
    alternate_names:  string[];
    species:          string;
    gender:           string;
    house:             "Gryffindor" | "Slytherin" | "Ravenclaw" | "Hufflepuff" | ""
    dateOfBirth:      string;
    yearOfBirth:      number;
    wizard:           boolean;
    ancestry:         string;
    eyeColour:        string;
    hairColour:       string;
    wand:             Wand;
    patronus:         string;
    hogwartsStudent:  boolean;
    hogwartsStaff:    boolean;
    actor:            string;
    alternate_actors: never[];
    alive:            boolean;
    image:            string;
}

export interface Wand {
    wood:   string;
    core:   string;
    length: number;
}
export type CharacterId = string